language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - npm install
  - npm run generate
  - npm rebuild node-sass

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 594c2a748618670b9ccfa64182e1504cb4ecc7b9
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master