language: node_js
node_js:
  - "12"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - npm install
  - npm run generate
  - npm rebuild node-sass

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 7204e61fb9385107e340eca8a9266900e0fdf218
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master